config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get '/about',to:'pages#about'
  get '/contact',to:'pages#contact'

  get '/signup',to:'users#new'
  post '/signup',to:'users#create'

  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'

  resources :users
  resources :account_activations, only:[:edit]
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :posts
  resources :tags,except:[:index,:show]
  resources :comments, only:[:create]
  resources :replies, only:[:create]
  resources :messages, only:[:index,:create,:destroy]
  resources :dashboard, only: [:index]

  match 'all_messages_delete', to: 'messages#delete_all', via: :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

	has_many :posts,dependent: :destroy
	has_many :tags,dependent: :destroy
	has_many :comments,dependent: :destroy
	has_many :replies,dependent: :destroy

	attr_accessor :remember_token, :activation_token, :reset_token
	before_save :downcase_email
	before_create :create_activation_digest

	extend FriendlyId
  	friendly_id :name, use: :slugged

	validates :name, presence: true, length:{ maximum:50 }
	REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length:{ maximum:255 },
									  format:{ with: REGEX },
									  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	#返回指定字符串的哈希值
	def self.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	#返回一个随机令牌
	def self.new_token
		SecureRandom.urlsafe_base64
	end

	#为了持久保存会话，在数据库中记住用户
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	#如果指定的令牌和摘要匹配，返回true
	def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end


	#忘记用户
	def forget
		update_attribute(:remember_digest, nil)
	end

	# 激活账户
	def activate
		update_columns(activated: true, activated_at: Time.now.to_s(:db))
	end

	# 发送激活邮件
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	# 设置密码重设相关的属性
	def create_reset_digest
        self.reset_token = User.new_token
        update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.now.to_s(:db))
	end

	# 发送密码重设邮件
	def send_password_reset_email
	    UserMailer.password_reset(self).deliver_now
	end

	# 如果密码重设请求超时了，返回 true
	def password_reset_expired?
	   reset_sent_at < 1.hours.ago
	end



	private

	# 把电子邮件地址转换成小写
	def downcase_email
		self.email = email.downcase
	end

	# 创建并赋值激活令牌和摘要
	def create_activation_digest
        self.activation_token  = User.new_token
		self.activation_digest = User.digest(activation_token)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :get_id, only:[:show,:edit,:update]
  before_action :logged_in_user, only:[:index,:edit,:update,:destroy,:show]
  before_action :correct_user, only:[:edit,:update]
  before_action :admin_user, only:[:index,:destroy]

  layout 'session', only:[:new,:create,:edit,:update]

  def index
    if params[:order]
       @users = User.where(activated: true).paginate(page: params[:page]).order(created_at: params[:order])
    else
      @users = User.where(activated: true).paginate(page: params[:page]).order(created_at: :desc)
    end
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      @user.send_activation_email
      flash[:success] = "请登陆你的邮箱以激活账号."
      redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def show
    @reply = Reply.new
    redirect_to root_url and return unless @user.activated == true
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "用户账号更新成功!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.friendly.find(params[:id]).destroy
    flash[:success] = "用户删除成功"
    redirect_to users_url
  end

  private

  def user_params
  	params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

  def get_id
    @user = User.friendly.find(params[:id])
  end

    # 确保是正确的用户 
  def correct_user
    @user = User.friendly.find(params[:id])
    redirect_to(root_url) unless current_user?(@user) || current_user.admin
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h2>请填写正确的内容</h2>
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages',object: @user %>
	<div>
		<label for="name"><span class="fa fa-pencil fa-fw"></span> 昵称</label>
		<%= f.text_field :name, placeholder: "账户昵称"%>
	</div>
	<div>
		<label for="account"><span class="fa fa-user fa-fw"></span> 邮箱</label>
		<%= f.text_field :email,placeholder: "你的邮箱地址" %>
	</div>
	<div>
		<label for="password"><span class="fa fa-lock fa-fw"></span> 密码</label>
		<%= f.password_field :password,placeholder: "你的密码" %>
	</div>
	<div>
		<label for="password_confirmation"><span class="fa fa-lock fa-fw"></span> 密码</label>
		<%= f.password_field :password_confirmation,placeholder: "密码确认" %>
	</div>
	<div>
		<%= f.submit "Sign Up" %>
	</div>
<% end %>

app/views/users/_user.html.erb
<li>
	<h3>
		<%= link_to user.name ,user %>
		<%= link_to user.email ,user, class: 'category' %>
	</h3>
	<span>Create_at: <%= user.created_at %></span>
	<div class="control" style="margin-top: 20px;">
		<%= link_to 'Edit',edit_user_path(user),class: 'edit'%>
		<% if current_user.admin? && !current_user?(user) %>
			<%= link_to 'Delete',user,class: 'destroy',method: :delete, data:{ confirm: "你确定要删除#{ user.name }吗？" } %>
		<% end %>
	</div>	
</li>

app/views/users/edit.html.erb
<% provide(:title,'Edit Profile') %>
<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title,'AllTourist') %>
<div class="list">
	<ul class="left">
		<li>
			<span class="category">Sorting of Posts</span>
			<ul>
				<li><%= link_to 'Desc of Time(倒序)', users_path(order: 'desc') %></li>
				<li><%= link_to 'Asc of Time(正序)', users_path(order: 'asc') %></li>
			</ul>
		</li>
	</ul>
</div>
<div class="maincontent">
	<h2>All Tourists</h2>
	<ul class="post-list">
		<% @users.each do |user| %>
			<%= render user %>
		<% end %>
	</ul>
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title,'New User') %>
<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title,'MyProfile') %>
<div class="list">
	<ul>
		<li>
			<%= current_user.admin ? image_tag("pic.jpg") : image_tag("user.jpg") %>
		</li>
		<li>
			<span class="category">Some of My Data</span>
			<ul>
				<li><a>Name: <%= @user.name %></a></li>
				<li><a><%= @user.email %></a></li>
				<li><%= link_to 'Edit Profile',edit_user_path(@user),class: 'btn' %></li>
			</ul>
		</li>
	</ul>
</div>
<div class="maincontent">
	<h2>Some of My Data</h2>
	<div class="introduce">
		<h3>Account Type: <strong style="color:#26abe2;"">Administrator</strong></h3>
		<p><strong>The following are all my historical reviews<br>以下是我全部的历史评论</strong>
		</p>
		<ul style="padding-left:0;">
			<li>
				<div class="comments">
					<% @user.comments.each.with_index do |c,index| %>
					<div class="comment_c">
						<div class="left_img">
							<%= image_tag "#{img_chose(c)}" %>
						</div>
						<div class="right_data">
							<div>
								<p>For: <strong><%= link_to c.post.try(:title),post_path(c.post),class: 'time' %></strong> 
									<span class="reply_button">回复</span> 
									<% if c.replies.count > 0 %>
										<span class="reply_list_button">查看回复</span>
									<% end %>
								</p>
								<p class="data_c"><%= c.content %></p>
							</div>
							<%= render 'shared/reply_list', c: c %>
						</div>
					</div>
					<% end %>
				</div>
			</li>
		</ul>
	</div>
</div>