config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get '/about',to:'pages#about'
  get '/contact',to:'pages#contact'

  get '/signup',to:'users#new'
  post '/signup',to:'users#create'

  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'

  resources :users
  resources :account_activations, only:[:edit]
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :posts
  resources :tags,except:[:index,:show]
  resources :comments, only:[:create]
  resources :replies, only:[:create]
  resources :messages, only:[:index,:create,:destroy]
  resources :dashboard, only: [:index]

  match 'all_messages_delete', to: 'messages#delete_all', via: :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :user
	has_many :posts,dependent: :destroy
	validates :name, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	before_action :logged_in_user
  	before_action :admin_user

  def new
  	@tags = Tag.all.paginate(page: params[:page], per_page: 5)
  	@tag = Tag.new
  end

  def create
  	@tag = Tag.new(tag_params)
  	@tag.user_id = current_user.id
  	if @tag.save
  		flash[:success] = "#{@tag.name} 标签创建成功."
  	else
  		flash[:danger] = "因错误创建失败."
  	end
  	redirect_back(fallback_location: new_tag_path)
  end

  def edit
  	@tag = Tag.find(params[:id])
  end

  def update
  	@tag = Tag.find(params[:id])
  	if @tag.update_attributes(tag_params)
  		flash[:success] = "标签资料更新成功."
  	else
  		flash[:danger] = "标签资料更新失败."
  	end
  	redirect_back(fallback_location: new_tag_path)
  end

  def destroy
  	Tag.find(params[:id]).destroy
  	flash[:danger] = "标签删除成功."
  	redirect_back(fallback_location: new_tag_path)
  end

  private

  def tag_params
  	params.require(:tag).permit(:name,:introduce)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
	<div>
		<label for="name">Name of Tag</label>
		<%= f.text_field :name, placeholder:'The name of Tag',class: 'post_title' %>
	</div>
	<div>
		<label for="introduce">Tags简介</label>
		<%= f.cktext_area :introduce,:class => 'ckeditor' %>
	</div>
	<div>
		<%= f.submit value:'Submit' %>
	</div>
<% end %>

app/views/tags/edit.html.erb
<% provide(:title,"Edit Tags") %>

<%= render 'shared/list' %>
<div class="maincontent">
	<h2>Edit the Tags</h2>
	<div class="edit_f">
		<%= render 'form' %>
	</div>
</div>

app/views/tags/new.html.erb
<% provide(:title,"Create Tags") %>

<%= render 'shared/list' %>
<div class="maincontent">
	<ul class="post-list">
		<h2>All the Tags</h2>
		<% if @tags.count == 0 %>
			<h3 style="background-color: #ccc;border-radius: 4px; padding: 10px 20px;">暂无标签.</h3>
		<% else %>
			<% @tags.each do |tag| %>
				<li>
					<h3>
						<%= link_to tag.name,'' %>
						<span class="category"><%= time_now(tag.created_at) %></span>
					</h3>
					<span style="color:#26abe2;"><%= tag.user.try(:name) %></span>
					<% if tag.introduce.empty? %>
						<p>该标签没有撰写简介.</p>
					<% else %>
						<p><%= truncate(strip_tags(tag.introduce),length:140,separate: '') %></p>
					<% end %>	
					<div class="control">
						<%= link_to 'Edit',edit_tag_path(tag),class: 'edit' %>
						<%= link_to 'Delete',tag_path(tag),method: :delete,data:{confirm:"你确定要删除 #{tag.name} 吗?"},class:'destroy' %>
					</div>
				</li>
			<% end %>
		<% end %>
	</ul>
	<%= will_paginate @tags %>
	<h2>Create the Tags</h2>
	<div class="edit_f">
		<%= render 'form' %>
	</div>
</div>