config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get '/about',to:'pages#about'
  get '/contact',to:'pages#contact'

  get '/signup',to:'users#new'
  post '/signup',to:'users#create'

  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'

  resources :users
  resources :account_activations, only:[:edit]
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :posts
  resources :tags,except:[:index,:show]
  resources :comments, only:[:create]
  resources :replies, only:[:create]
  resources :messages, only:[:index,:create,:destroy]
  resources :dashboard, only: [:index]

  match 'all_messages_delete', to: 'messages#delete_all', via: :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :tag
  has_many :comments, dependent: :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged
  
  default_scope ->  { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :publish, presence: true

  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  include Commond

  before_action :get_name, only:[:show,:edit,:update]
  before_action :logged_in_user, except:[:show]
  before_action :admin_user, except:[:show]


  def index
    @tags = Tag.all
    id = Tag.where(name: params[:tip]).ids
    post(params[:order],params[:tip],id)
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
  	if @post.save
  		flash[:success] = "文章创建成功!"
  		redirect_to posts_url
  	else
  		flash[:danger] = "文章因某个错误创建失败!"
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if @post.update_attributes(post_params)
  		flash[:success] = "文章内容更新成功."
  		redirect_to posts_url
  	else
  		flash[:danger] = "某个错误的输入导致更新失败."
  		render 'edit'
  	end
  end

  def show
    @comment = Comment.new
    @reply = Reply.new
  end

  def destroy	
  	Post.friendly.find(params[:id]).destroy
  	flash[:success] = "成功删除目标文章."
  	redirect_back(fallback_location: posts_url)
  end

  private

   def post_params
   	params.require(:post).permit(:title,:content,:publish,:tag_id)
   end

   def get_name
    @post = Post.friendly.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
	<div>
		<label for="title">Title of Post</label>
		<%= f.text_field :title, placeholder:'The title of Post',class: 'post_title' %>
	</div>
	<div>
		<label for="tag">Tag of Post</label>
		<%= f.select :tag_id, Tag.all.collect {|t| [t.name, t.id]}, name: "tags" %>
	</div>
	<div>
		<label for="post">Post内容</label>
		<%= f.cktext_area :content,:class => 'ckeditor' %>
	</div>
	<div>
		<%= f.check_box :publish %><span class="publish">If you want it to Publish?</span>
	</div>
	<div>
		<%= f.submit value:'Submit' %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title,"Edit Post") %>

<%= render 'list' %>
<div class="maincontent">
	<h2 id="title">Edit the Post</h2>
	<div class="edit_f">
		<%= render 'form' %>
	</div>
</div>

app/views/posts/index.html.erb
<% provide(:title,'My Posts') %>
<div class="list">
	<ul class="left">
		<li>
			<span class="category">System Classification</span>
			<ul>
				<li><%= link_to 'All Post', posts_path %></li>
				<% @tags.each do|tag| %>
				<li><%= link_to tag.name, posts_path(:tip => "#{tag.name}") %></li>
				<% end %>
			</ul>
		</li>
		<li>
			<span class="category">Sorting of Posts</span>
			<ul>
				<li><%= link_to 'Desc of Time(倒序)', posts_path(:tip => @type, :order => 'desc') %></li>
				<li><%= link_to 'Asc of Time(正序)', posts_path(:tip => @type, :order => 'asc') %></li>
			</ul>
		</li>
	</ul>
</div>
<div class="maincontent">
	<h2>
		<% if @type %>
			<%= @type %>
		<% else %>
			All Posts
		<% end %>
		<small style="color:#26abe2;"> (<%= @posts.count %>)</small>
	</h2>
	<ul class="post-list">
		<% if @posts.count > 0 %>
			<% @posts.each do |post| %>
				<li>
					<h3>
						<%= link_to truncate(post.title,length:30,separate:''),post_path(post) %>
						<%= link_to post.tag.try(:name),'#',class: 'category' %>
					</h3>
					<span><%= time_now(post.created_at) %></span>
					<span> | <%= post.publish %></span>
					<p><%= truncate(strip_tags(post.content),length:140,separate: '') %></p>
					<div class="control">
						<%= link_to 'Edit',edit_post_path(post),class: 'edit' %>
						<%= link_to 'Delete',post_path(post),method: :delete,data:{confirm:"你确定要删除 #{post.title} 吗?"},class:'destroy' %>
					</div>
				</li>
			<% end %>
		<% else %>
			<h3 style="background-color: #ccc;border-radius: 4px; padding: 10px 20px;">该分类下暂无文章.</h3>
		<% end %>
	</ul>
	<%= will_paginate %>
</div>

app/views/posts/new.html.erb
<% provide(:title,"Create Post") %>

<%= render 'shared/list' %>
<div class="maincontent">
	<h2 id="title">Create the Post</h2>
	<div class="edit_f">
		<%= render 'form' %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="list">
	<ul class="left">
		<li>
			<span class="category">Post's Structure</span>
			<ul>
				<li><a class="localtion" id='title'>Post's Title</a></li>
				<li><a class="localtion" id='data'>Post's Data</a></li>
				<li><a class="localtion" id='content'>Post's Content</a></li>
			</ul>
		</li>
		<li>
			<span class="category">Post's Comments</span>
			<ul>
				<li><a class="localtion" id='comment_w'>Comments' content</a></li>
				<li><a class="localtion" id='comment_d'>Comment</a></li>
			</ul>
		</li>
	</ul>
</div>
<div class="maincontent">
	<h2 id="title_l"><%= @post.title %></h2>
	<div class="post">
		<p id='data_l'><span><%= @post.user.try(:name) %></span><span>Date: <%= @post.created_at %></span></p>
		<p id="content_l">
			<div>
				<%= @post.content.html_safe %>
			</div>
		</p>
	</div>
	<h2 id="comment_w_l" style="font-size: 2rem;">The comments of the Post</h2>
	<div class="comments">
		<% @post.comments.each.with_index do |c,index| %>
		<div class="comment_c">
			<div class="left_img">
				<%= image_tag "#{img_chose(c)}" %>
			</div>
			<div class="right_data">
					<div>
						<p>Floor: <%= index+1 %> <span class="time"><%= time_now(c.created_at) %></span></p>
						<p>
							<strong><%= c.user.try(:name) %></strong> 
							<span class="reply_button">回复</span> 
							<% if c.replies.count > 0 %>
								<span class="reply_list_button">查看回复</span>
							<% end %>
						</p>
						<p class="data_c"><%= c.content %></p>
					</div>
				<%= render 'shared/reply_list', c: c %>
			</div>
		</div>
		<% end %>
	</div>
	<h2 id="comment_d_l" style="font-size: 2rem;">To Comment</h2>
	<div class="comment">
		<%= form_for @comment, url: comments_url do |f| %>
			<%= f.text_area :content, placeholder:'请输入您的评论内容' %>
			<%= f.hidden_field :post_id, value: @post.id %>
			<%= f.submit  value: '评论提交' %>
		<% end %>
	</div>
</div>