config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get '/about',to:'pages#about'
  get '/contact',to:'pages#contact'

  get '/signup',to:'users#new'
  post '/signup',to:'users#create'

  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'

  resources :users
  resources :account_activations, only:[:edit]
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :posts
  resources :tags,except:[:index,:show]
  resources :comments, only:[:create]
  resources :replies, only:[:create]
  resources :messages, only:[:index,:create,:destroy]
  resources :dashboard, only: [:index]

  match 'all_messages_delete', to: 'messages#delete_all', via: :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	has_many :replies,dependent: :destroy

	validates :content, presence: true
end

app/models/ip.rb
class Ip < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email,presence: true,format:{ with: REGEX }
	validates :name,presence: true
	validates :content,presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :tag
  has_many :comments, dependent: :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged
  
  default_scope ->  { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :publish, presence: true

  

end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  validates :content,presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :user
	has_many :posts,dependent: :destroy
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

	has_many :posts,dependent: :destroy
	has_many :tags,dependent: :destroy
	has_many :comments,dependent: :destroy
	has_many :replies,dependent: :destroy

	attr_accessor :remember_token, :activation_token, :reset_token
	before_save :downcase_email
	before_create :create_activation_digest

	extend FriendlyId
  	friendly_id :name, use: :slugged

	validates :name, presence: true, length:{ maximum:50 }
	REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length:{ maximum:255 },
									  format:{ with: REGEX },
									  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	#返回指定字符串的哈希值
	def self.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	#返回一个随机令牌
	def self.new_token
		SecureRandom.urlsafe_base64
	end

	#为了持久保存会话，在数据库中记住用户
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	#如果指定的令牌和摘要匹配，返回true
	def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end


	#忘记用户
	def forget
		update_attribute(:remember_digest, nil)
	end

	# 激活账户
	def activate
		update_columns(activated: true, activated_at: Time.now.to_s(:db))
	end

	# 发送激活邮件
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	# 设置密码重设相关的属性
	def create_reset_digest
        self.reset_token = User.new_token
        update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.now.to_s(:db))
	end

	# 发送密码重设邮件
	def send_password_reset_email
	    UserMailer.password_reset(self).deliver_now
	end

	# 如果密码重设请求超时了，返回 true
	def password_reset_expired?
	   reset_sent_at < 1.hours.ago
	end



	private

	# 把电子邮件地址转换成小写
	def downcase_email
		self.email = email.downcase
	end

	# 创建并赋值激活令牌和摘要
	def create_activation_digest
        self.activation_token  = User.new_token
		self.activation_digest = User.digest(activation_token)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include Commond

  def index
    if !Ip.where(ip_address: request.remote_ip)
      Ip.create(ip_address: request.remote_ip)
    end
    @tags = Tag.all
    id = Tag.where(name: params[:tip]).ids
    post(params[:order],params[:tip],id)
  end

  def about
  end

  def contact
    @message = Message.new
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	before_action :logged_in_user
  	before_action :admin_user

  def new
  	@tags = Tag.all.paginate(page: params[:page], per_page: 5)
  	@tag = Tag.new
  end

  def create
  	@tag = Tag.new(tag_params)
  	@tag.user_id = current_user.id
  	if @tag.save
  		flash[:success] = "#{@tag.name} 标签创建成功."
  	else
  		flash[:danger] = "因错误创建失败."
  	end
  	redirect_back(fallback_location: new_tag_path)
  end

  def edit
  	@tag = Tag.find(params[:id])
  end

  def update
  	@tag = Tag.find(params[:id])
  	if @tag.update_attributes(tag_params)
  		flash[:success] = "标签资料更新成功."
  	else
  		flash[:danger] = "标签资料更新失败."
  	end
  	redirect_back(fallback_location: new_tag_path)
  end

  def destroy
  	Tag.find(params[:id]).destroy
  	flash[:danger] = "标签删除成功."
  	redirect_back(fallback_location: new_tag_path)
  end

  private

  def tag_params
  	params.require(:tag).permit(:name,:introduce)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Sample Wanting"
		if page_title.empty?
			base_title
		else
			page_title + ' | ' + base_title
		end
	end

	def time_now time
		time.strftime("%d %b in %Y")
	end

	def img_chose tip
		if tip.user.try(:admin)
			'pic.jpg'
		else
			'user.jpg'
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	#登入指定用户
	def log_in(user)
		session[:user_id] = user.id
	end

	#在持久会话中记住用户
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	# 如果指定用户是当前用户，返回 true 
	def current_user?(user)
		user == current_user
	end

	#返回当前登陆的用户
	def current_user
		if(user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif(user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(:remember, cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end	

	#如果用户已经登陆返回true,否则false
	def logged_in?
		!current_user.nil?
	end

	#忘记持久会话
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	#退出当前用户
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<p>&copy All right belongs to James 2018-2019</p>
	</div>
</footer>

<div class="extra">
	<div class="notice">
		<span class="fa fa-envelope-open fw notice_button" title="通知公告"></span>
		<div class="notice_m">
			<h3>通知公告<span class="fa fa-close fw notice_close"></span></h3>
			<p>本站仅用于学习交流,严禁各种灌水、广告行为,违规者删号处置,并将拒绝相同Ip浏览及登入.<br>如有任何疑问,欢迎留言或来信,更多学习交流请移步QQ学习群: <span style="color: #26abe2;">684746447</span></p>
		</div>
	</div>
	<div class="top">
		<span class="fa fa-chevron-up fw"></span>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="font">
	<nav>
		<div class="container clear">
			<div class="logo">
				<%= link_to root_path do %>
					<h1><span style="color: #26abe2;">Want</span>ing</h1></a>
				<% end %>
			</div>
			<div class="mobile-button">
				<button><span class="fa fa-bars"></span></button>
			</div>
			<div class="link clear">
				<div class="navbar">
					<ul class="clear">
						<li><%= link_to 'Blog', root_path %></li>
						<li><%= link_to 'About', about_path %></li>
						<li><%= link_to 'Contact', contact_path %></li>
					</ul>
				</div>
				<div class="dropmenu">
					<ul class="clear">
						<li>
							<% if logged_in? %>
								<a class="DownButton">My Account <span class="fa fa-angle-down" style="padding-left: 10px;"></span></a>
								<ul class="downmenu">
									<li><%= link_to 'My Profile',current_user %></li>
									<li><%= link_to 'My All Post', posts_path %></li>
									<% if current_user.admin? %>
										<li><%= link_to 'To Dashboard',dashboard_index_path %></li>
									<% end %>
									<hr style="width: 95%; background-color: #f0f0f0; border-color: transparent;">
									<li><%= link_to 'Log Out',logout_path,method: :delete %></li>
								</ul>
							<% else %>
								<%= link_to 'Login / SignUp', login_path,class: 'DownButton'%>
							<% end %>
							
						</li>
					</ul>
				</div>
			</div>
		</div>
	</nav>
	<div class="word font">
		<div class="container">
			<h2>
				I am <strong>Wanting</strong> to be closer to perfection...
			</h2>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1,user-scalable=no">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>

      <% flash.each do |message_type, message| %>
          <div class="container flash">
            <div class="flash-message alert alert-<%= message_type %>"><%= message %> <span class="fa fa-close fw close"></span></div>
          </div>
      <% end %>

	<div class="content">
		<div class="container">
			<div class="flex">
				<%= yield %>
			</div>
		</div>
	</div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1,user-scalable=no">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<header class="font" style="min-width: 415px;">
    <nav>
      <div class="container clear">
        <div class="logo">
          <a href="#"><h1><span style="color: #26abe2;">Want</span>ing</h1></a>
        </div>
        <div class="mobile-button">
          <button><span class="fa fa-bars"></span></button>
        </div>
        <div class="link clear">
          <div class="dropmenu">
            <ul class="clear">
              <li>
                <% if yield(:title)== 'Login User' %>
                  <%= link_to signup_path,class: 'DownButton' do %>
                    Don't have account?<strong style="color:#26abe2;padding-left: 10px;">Sign up</strong>
                  <% end %>
                <% elsif(yield(:title)== 'New User') %>
                  <%= link_to login_path,class: 'DownButton' do %>
                    Already have account?<strong style="color:#26abe2;padding-left: 10px;">Log in</strong>
                  <% end %>
                <% else %>
                  <strong style="color:#26abe2;padding-left: 10px;">Hope You Have Good Time!</strong>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </header>

  <% flash.each do |message_type, message| %>
      <div class="container flash">
        <div class="flash-message alert alert-<%= message_type %>"><%= message %> <span class="fa fa-close fw close"></span></div>
      </div>
  <% end %>

      
  <div class="session">
    <div class="container">
      <div class="webTopic">
        <h2>欢迎来到<strong class='font'>Wanting</strong>这个“世界”</h2>
        <p>衷心感谢您的光临</p>
        <p>希望您能在这里有新的体会</p>
        <p>/*但请报以学习或指点的心态正确浏览、使用*/</p>
      </div>
      <div class="session_form">
        <div class="form">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title,'About') %>
<div class="list">
	<ul>
		<li>
			<%= image_tag "pic.jpg" %>
		</li>
		<li>
			<span class="category">Getting Started</span>
			<ul>
				<li><a class="localtion" id='me'>Who I am</a></li>
				<li><a class="localtion" id='web'>'Wanting'是一个怎样的网站</a></li>
				<li><a class="localtion" id='read'>你将阅读到的内容概述</a></li>
				<li><a class="localtion" id='comment'>欢迎积极的评论</a></li>
			</ul>
		</li>
		<li>
			<span class="category">Matters Needing Attention</span>
			<ul>
				<li><a class="localtion" id='reprint'>转载内容注意事项</a></li>
				<li><a class="localtion" id='consultation'>Consultation</a></li>
			</ul>
		</li>
	</ul>
</div>
<div class="maincontent">
	<h2>Getting Started</h2>
	<div class="introduce">
		<p id="me_l">" Hi , I am <strong>James</strong>. "</p>
		<p>"A <strong>'LITTLE ROOKIE'</strong> in the near future." <br>一个刚入行的<strong>"小菜鸟"</strong> .</p>
		<p id="web_l">Here is my technical blog platform, I will upload some articles here to record my learning experience and understanding. Hope can help you. Of course, thank you sincerely for your reading. If you find the content wrong, I hope it can be pointed out in time. Thank you here! <br>这里是我的个人技术博客，我将在这里上传记录我学习过程及经验的文章。希望这些能够帮助到你。当然，感谢你的阅览。如果你在阅读过程中发现某些错误，请联系我及时加以改正，在此再次感谢！</p>
		<p id="read_l" class="localtion"><strong>Here, the content of the Bowen covers the following:<br>在这里，博文的内容大致涵盖以下内容:</strong>
			<ul class="introduce-list">
				<li>Development of some components of static web pages and learning<br>静态网页部分组件的开发和学习</li>
				<li>Related application technology of JavaScript <br>javascript的相关应用技术</li>
				<li>Ruby on rails learning and practical record <br>ruby on rails的学习及实战笔录</li>
				<li>Learning and practical application of react-native <br>react-native的学习及实战应用</li>
			</ul>
		</p>
		<p id="comment_l"><strong>You are always welcome to comment and speak under the article, but please do not show the following: <br>随时欢迎你在文章下面进行评论和发言，但请不要出现下列情况:</strong>
			<ul class="introduce-list">
				<li>Maliciously, fabricating comments, or sending out bad information <br>恶意、捏造评论或散发不良信息</li>
				<li>"Add water" <br>灌水行为</li>
			</ul>
		</p>
	</div>
	<h2>Matters Needing Attention</h2>
	<div class="introduce">
		<p id="reprint_l">When you want to reprint the article resources in the website, please read the following: <br>当你想要转载网站内的文章资源时，请先阅读以下内容:
			<ul class="introduce-list">
				<li>Sometimes the blogger will forward some technical content. If the copyright notes are ignored, please let me know in time. <br>有时候博主会转发一些技术内容，如果有版权注释被忽略，请及时通知我</li>
				<li>The blog article is allowed to reprint, but please mark the source <br>博客的文章允许转载，但请标注出处</li>
			</ul>
		</p>
		<p id="consultation_l">If you have more questions, welcome to QQ<strong>684746447</strong>. <br>如果你有更多其他的疑问，欢迎通过QQ<strong>684746447</strong>咨询</p>
	</div>
</div>

app/views/pages/contact.html.erb
<% provide(:title,'Contact') %>
<div class="list">
	<ul class="left">
		<li>
			<span class="category">Something Talk</span>
			<ul>
				<li><a href="#">确保你的邮箱正在使用</a></li>
				<li><a href="#">确认你的昵称</a></li>
				<li><a href="#">请正确表述你的信息内容</a></li>
				<li><a href="#">请不要多次重复发送</a></li>
			</ul>
		</li>
		<li>
			<span class="category">About Reply</span>
			<ul>
				<li><a href="#">回复将在3～5个工作日内完成</a></li>
				<li><a href="#">请耐心等待</a></li>
			</ul>
		</li>
	</ul>
</div>
<div class="maincontent">
	<h2>Write Down Here</h2>
	<div class="contact_f">
		<%= form_for @message, url: messages_url do |f| %>
			<div>
				<label for="name">Name <small>(正确的姓名或称号)</small></label>
				<%= f.text_field :name, placeholder: 'Please write down your name here' %>
			</div>
			<div>
				<label for="email">Email <small>(确保正在使用)</small></label>
				<%= f.text_field :email, placeholder: 'Please write down your email here' %>
			</div>
			<div>
				<label for="Introduce">Type <small>(eg: 错误 问题 or 其他类型,非必填)</small></label>
				<%= f.text_field :introduce, placeholder: 'Please write down the type of content' %>
			</div>
			<div>
				<label for="content">Content <small>(请详细表述您的问题)</small></label>
				<%= f.text_area :content, placeholder: "It\'s best limit to 100~150 words" %>
			</div>
			<div>
				<%= f.submit value: 'Submit' %>
			</div>
		<% end %>
	</div>
</div>

app/views/pages/index.html.erb
<% provide(:title,'Blog') %>
<div class="list">
	<ul class="left">
		<li>
			<span class="category">System Classification</span>
			<ul>
				<li><%= link_to 'All Posts', root_path %></li>
				<% @tags.each do|tag| %>
					<li><%= link_to tag.name, root_path(:tip => "#{tag.name}") %></li>
				<% end %>
			</ul>
		</li>
		<li>
			<span class="category">Sorting of Posts</span>
			<ul>
				<li><%= link_to 'Desc of Time(倒序)', root_path(:tip => @type, :order => 'desc') %></li>
				<li><%= link_to 'Asc of Time(正序)', root_path(:tip => @type, :order => 'asc') %></li>
			</ul>
		</li>
	</ul>
</div>
<div class="maincontent">
	<h2>
		<% if @type %>
			<%= @type %>
		<% else %>
			All Posts
		<% end %>
	</h2>
	
	<ul class="post-list">
		<% if @posts.count > 0 %>
			<% @posts.each do |post| %>
				<li>
					<h3>
						<%= link_to truncate(post.title,length:30,separate:''),post_path(post) %>
						<%= link_to post.tag.try(:name),'#',class: 'category' %>
					</h3>
					<span><%= "#{time_now(post.created_at)} by " %></span>
					<span style="color:#26abe2;"><%= post.user.try(:name) %></span>
					<p><%= truncate(strip_tags(post.content),length:140,separate: '') %></p>
				</li>
			<% end %>
		<% else %>
			<h3 style="background-color: #ccc;border-radius: 4px; padding: 10px 20px;">该分类下暂无文章.</h3>
		<% end %>
	</ul>
	
	<%= will_paginate @posts %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div class="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %> :
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li> <% end %>
		</ul>
		<a class='close'>了解</a>
	</div>
<% end %>

app/views/shared/_list.html.erb
<div class="list">
	<ul class="left">
		<li>
			<span class="category">Control Panel</span>
			<ul>
				<li><%= link_to 'DashBoard',dashboard_index_path %></li>
				<li><%= link_to 'Create New Post',new_post_path %></li>
				<li><%= link_to 'Create New Tag',new_tag_path %></li>
				<li><%= link_to 'Message', messages_path %></li>
			</ul>
		</li>
	</ul>
</div>

app/views/shared/_order.html.erb
<span class="category">Sorting of Posts</span>
<ul>
	<li><%= link_to 'Desc of Time(倒序)', posts_path(order:'desc') %></li>
	<li><%= link_to 'Desc of Time(正序)', posts_path(order:'asc') %></li>
</ul>

app/views/shared/_reply_list.html.erb
<div class="reply_content">
	<h2 style="font-size: 1.2rem;padding: 5px 0;">回复列表</h2>
	<div class="reply_list">
		<% c.replies.each.with_index do |r,index| %>
		 	<div class="comment_c">
				<div class="left_img">
					<%= image_tag("#{img_chose(r)}") %>
				</div>
				<div class="right_data">
					<div>
						<p><strong><%= r.user.try(:name) %></strong> <span class="time"><%= time_now(r.created_at) %></span></p>
						<p class="data_c"><%= r.content %></p>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>
<div class="reply">
	<%= form_for @reply, url: replies_url do |f| %>
		<%= f.text_area :content, placeholder:'请输入您的回复内容' %>
		<%= f.hidden_field :comment_id, value: c.id %>
		<%= f.submit  value: '回复提交' %>
	<% end %>
</div>